version: '3.8'
name: funfly
# services - here i am going to list containers that i want to build
# each service, actually describes a docker run command
services:
  # docker run --name weezer-db -d -e MYSQL_ALLOW_EMPTY_PASSWORD=1 -e MYSQL_DATABASE=weezer -e MYSQL_TCP_PORT=3306 -p 3308:3306  deanst/weezer-db:1.0.0
  database:
    container_name: funfly-db-compose
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_DATABASE=funfly
      - MYSQL_TCP_PORT=3306
    ports:
      - "3309:3306"
    # image: deanst/weezer-db:1.0.0
    build: ./database
    volumes:
      - funflydata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  # docker run --name weezer-backend -d -p 3010:3000 -e NODE_ENV=docker deanst/weezer-backend:3.0.0
  backend:
    container_name: funfly-backend-compose
    environment:
      - NODE_ENV=compose
    ports:
      - "3020:3000"
    build: ./backend
    depends_on:
      database:
        condition: service_healthy
  # docker run --name weezer-frontend -d -p 3011:5173 shaharsol/weezer-frontend:1.0.1
  frontend:
    container_name: funfly-frontend-compose
    ports:
      - "3012:80"
    build: 
      context: ./frontend
      dockerfile: Dockerfile.compose

# docker run --name localstack -d --rm -it -p 4566:4566 -p 4510-4559:4510-4559 localstack/localstack
  localstack:
    container_name: funfly-localstack-compose
    ports:
      - 4566:4566
      - 4510-4559:4510-4559
    image: localstack/localstack
    environment:
      - SERVICES=s3
      - DEBUG=1
      - PERSISTENCE=1
    volumes:
      - funfly_s3localdata:/var/lib/localstack
  io:
    container_name: funfly-io-compose
    ports:
      - "3022:3004"
    build: ./io

volumes:
  funflydata:
  funfly_s3localdata: